global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['backend-transcendence:8000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter-transcendence:9100']
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter-transcendence:9187']
